name: CI

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry (zkSync version)
        uses: matter-labs/foundry-zksync-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Run Forge build (EVM)
        run: forge build --sizes

      - name: Run EVM tests
        run: forge test --match-path "test/ethereum/*" -vvv

      - name: Run Forge build (zkSync)
        run: FOUNDRY_PROFILE=zksync forge build --zksync --system-mode=true --sizes

      - name: Run zkSync tests
        run: FOUNDRY_PROFILE=zksync forge test --match-path "test/zksync/*" --zksync --system-mode=true -vvv